version: "3.9"
services:
  postgres:
    image: postgres:13.3
    volumes:
      - dockerpgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "polyclinic_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
volumes:
  dockerpgdata: